# Generated by Django 5.1.6 on 2025-07-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='DateofBirth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='fullname',
        ),
    ]
